clubs/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path


from . import views

app_name = 'clubs'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:club_id>/', views.detail, name='detail'),
    path('<int:club_id>/manage/', views.manage, name='manage'),
    path('<int:club_id>/manage/contacts/', views.edit_club_contacts, name='edit-contacts'),
    # path('manage/<int:club_id>/umpires/', views.edit_club_umpires, name='edit-umpires'),
    path('<int:club_id>/members/', views.MemberList.as_view(), name='members-list'),
    path('api/<int:club_id>/members/', views.ClubMemberListAPI.as_view(), name='api-members-list'),
    path('api/members/', views.MemberListAPI.as_view(), name='api-all-members-list'),
    path('<int:club_id>/members/<int:pk>/', views.MemberDetail.as_view(), name='members-detail'),
    path('<int:club_id>/members/request-transfer/', views.request_transfer, name='request-transfer'),
    path('transfer/', views.AdminMemberTransfer.as_view(), name='admin-member-transfer'),
    path('members/register/', views.AdminMemberRegister.as_view(), name='admin-member-register'),
    path('<int:club_id>/admin/set-main-contact/', views.AdminSetMainClubContact.as_view(), name='admin-set-main-contact')
]

home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('rules', views.rules, name='rules'),
    path('contact', views.contact, name='contact'),
    path('thanks', views.thanks, name='thanks'),
    path('help', views.help, name='help')
]

nehlwebsite/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

from . import settings

from nehlwebsite import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('clubs/', include('clubs.urls')),
    path('fixtures/', include('fixtures.urls.fixtures')),
    path('fixtures/cancellations/', include('fixtures.urls.cancellations')),
    path('fixtures/rearrangements/', include('fixtures.urls.rearrangements')),
    path('fixtures/competitions/', include('fixtures.urls.competitions')),
    path('teams/', include('teams.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile', views.profile, name='profile')
]

# urlpatterns += path(settings.MEDIAFILES_LOCATION, 'https://nehl-web-files.s3.eu-west-2.amazonaws.com/')

fixtures/models.py
from django.db import models
from django.conf import settings

from fixtures.utils.general import get_file_path


class Season(models.Model):
    years = models.CharField(max_length=6)
    display_name = models.CharField(max_length=7)
    teams = models.ManyToManyField('teams.Team')
    competition = models.ForeignKey('fixtures.Competition', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.display_name + ' - ' + self.competition.__str__()


class Competition(models.Model):
    name = models.CharField(max_length=50)
    short_name = models.CharField(max_length=5)
    parent_competition = models.ForeignKey('Competition',
                                           on_delete=models.SET_NULL,
                                           null=True,
                                           related_name='child_competition',
                                           blank=True
                                           )
    officials = models.ManyToManyField('CompetitionOfficial', blank=True)
    rules = models.ManyToManyField('RuleSet', blank=True)
    config = models.ManyToManyField('CompetitionConfigItem', blank=True)
    current_season = models.OneToOneField('Season',
                                          on_delete=models.SET_NULL,
                                          related_name='competition_current',
                                          null=True, blank=True)

    def __str__(self):
        return self.name


class CompetitionConfigItem(models.Model):
    key = models.CharField(max_length=25)
    value = models.BooleanField()

    def __str__(self):
        return self.key + ': ' + self.value.__str__()


class LeagueStanding(models.Model):
    league = models.ForeignKey('Competition', on_delete=models.CASCADE)
    team = models.ForeignKey('teams.Team', on_delete=models.CASCADE)
    season = models.ForeignKey('Season', on_delete=models.CASCADE)
    num_played = models.PositiveIntegerField(default=0)
    num_won = models.PositiveIntegerField(default=0)
    num_lost = models.PositiveIntegerField(default=0)
    num_drawn = models.PositiveIntegerField(default=0)
    goal_difference = models.IntegerField(default=0)
    total_points = models.IntegerField(default=0)


class Penalty(models.Model):
    description = models.CharField(max_length=400)

    def __str__(self):
        return self.description

    class Meta:
        verbose_name_plural = 'penalties'


class Rule(models.Model):
    number = models.IntegerField()
    penalty = models.ManyToManyField('Penalty', blank=True)

    class Meta:
        ordering = ['number']

    def __str__(self):
        return self.ruleset_set.first().__str__() + " - " + self.number.__str__()


class RuleSet(models.Model):
    number = models.IntegerField()
    name = models.CharField(max_length=50)
    rules = models.ManyToManyField('Rule', blank=True)

    class Meta:
        ordering = ['number']

    def __str__(self):
        return self.name


class RuleParagraph(models.Model):
    number = models.IntegerField()
    content = models.CharField(max_length=500)
    rule = models.ForeignKey('Rule', on_delete=models.CASCADE)

    class Meta:
        ordering = ['number']

    def __str__(self):
        return self.content


class Venue(models.Model):
    name = models.CharField(max_length=50)
    street_name = models.CharField(max_length=50, default='')
    postcode = models.CharField(max_length=10)

    def __str__(self):
        return self.name


class VenueUseType(models.Model):
    user = models.ForeignKey('clubs.Club', on_delete=models.CASCADE)
    venue = models.ForeignKey(Venue, on_delete=models.CASCADE)
    use_type = models.CharField(max_length=30)


class Fixture(models.Model):
    season = models.ForeignKey(Season, on_delete=models.CASCADE)
    competition = models.ForeignKey(Competition, on_delete=models.CASCADE)
    venue = models.ForeignKey(Venue, on_delete=models.SET_NULL, null=True, blank=True)
    team_a = models.ForeignKey('teams.Team',
                               related_name='team_a_fixtures',
                               on_delete=models.CASCADE,
                               null=True
                               )
    team_b = models.ForeignKey('teams.Team',
                               related_name='team_b_fixtures',
                               on_delete=models.CASCADE,
                               null=True
                               )
    date = models.DateField()
    time = models.TimeField(null=True, blank=True)
    umpire_a = models.ForeignKey('Umpire',
                                 related_name='fixtures_as_umpire_a',
                                 on_delete=models.SET_NULL,
                                 null=True, blank=True)
    umpire_b = models.ForeignKey('Umpire',
                                 related_name='fixtures_as_umpire_b',
                                 on_delete=models.SET_NULL,
                                 null=True, blank=True)
    match_card_submission_url = models.CharField(max_length=300, null=True, blank=True)
    result = models.OneToOneField('FixtureResult', on_delete=models.CASCADE, null=True, blank=True)
    metadata = models.OneToOneField('FixtureMetadata', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.date.__str__() + ' - ' + self.team_a.__str__() + " vs " + self.team_b.__str__()


class FixtureResult(models.Model):
    team_a_score = models.PositiveSmallIntegerField(default=0)
    team_b_score = models.PositiveSmallIntegerField(default=0)
    team_a_points = models.IntegerField(default=0)
    team_b_points = models.IntegerField(default=0)
    draw = models.BooleanField(default=False)
    winner = models.ForeignKey('teams.Team', related_name='wins', on_delete=models.SET_NULL, null=True, blank=True)
    loser = models.ForeignKey('teams.Team', related_name='losses', on_delete=models.SET_NULL, null=True, blank=True)
    complete = models.BooleanField(default=False)

    def __str__(self):
        if self.draw:
            return '{team_a} - {team_b} draw'.format(team_a=self.fixture.team_a, team_b=self.fixture.team_b)
        else:
            return '{winner} beat {loser}'.format(winner=self.winner, loser=self.loser)


def get_file_path(instance, filename):
    import uuid
    import os

    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('uploads/match_cards', filename)


class FixtureMetadata(models.Model):
    match_card_image = models.ImageField(upload_to=get_file_path, null=True)
    match_card_image_submitted = models.BooleanField(default=False)
    squad_a_selected = models.BooleanField(default=False)
    squad_b_selected = models.BooleanField(default=False)
    scorers_submitted = models.BooleanField(default=False)
    personal_penalties_submitted = models.BooleanField(default=False)
    start_time_submitted = models.BooleanField(default=False)

    time_match_card_image_submitted = models.DateTimeField(null=True)
    time_squad_a_selected = models.DateTimeField(null=True)
    time_squad_b_selected = models.DateTimeField(null=True)
    time_scorers_submitted = models.DateTimeField(null=True)
    time_penalties_submitted = models.DateTimeField(null=True)
    time_match_card_complete = models.DateTimeField(null=True)
    time_start_time_submitted = models.DateTimeField(null=True)

    umpire_a_signed = models.BooleanField(null=True)
    umpire_b_signed = models.BooleanField(null=True)
    captain_a_signed = models.BooleanField(null=True)
    captain_b_signed = models.BooleanField(null=True)

    issue_detected = models.BooleanField(default=False)


class MatchEvent(models.Model):
    time_occurred = models.DurationField(null=True, blank=True)
    appearance = models.ForeignKey('Appearance', on_delete=models.SET_NULL, null=True)
    fixture = models.ForeignKey('FixtureResult', on_delete=models.CASCADE)


class Goal(MatchEvent):
    pass


class PersonalPenalty(MatchEvent):
    awarded_by = models.ForeignKey('Umpire', on_delete=models.SET_NULL, null=True)
    penalty_type = models.ForeignKey('PersonalPenaltyType', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Personal penalties'


class PersonalPenaltyType(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Player(models.Model):
    member = models.ForeignKey('clubs.Member', on_delete=models.SET_NULL, null=True, blank=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    def __str__(self):
        if self.member is None:
            return self.first_name + ' ' + self.last_name
        else:
            return self.member.__str__()


class Appearance(models.Model):
    fixture = models.ForeignKey('Fixture', on_delete=models.CASCADE)
    player = models.ForeignKey('Player', on_delete=models.CASCADE)
    team = models.ForeignKey('teams.Team', on_delete=models.CASCADE)

    def __str__(self):
        return self.team.__str__() + ': ' + self.player.__str__()


class FixtureCancellation(models.Model):
    cancellation_reporter = models.ForeignKey('clubs.Member', on_delete=models.SET_NULL, null=True)
    fixture = models.ForeignKey(Fixture, on_delete=models.CASCADE)
    datetime_cancelled = models.DateTimeField()
    cancellation_reason = models.CharField(max_length=30)
    cancelled_by_team = models.ForeignKey('teams.Team', on_delete=models.SET_NULL, null=True)
    more_info = models.CharField(max_length=150)
    response = models.ForeignKey('CancellationResponse', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.fixture.__str__()


class CancellationResponse(models.Model):
    response = models.CharField(max_length=20)
    response_by = models.ForeignKey('fixtures.CompetitionOfficial', on_delete=models.SET_NULL, null=True)
    additional_comments = models.CharField(max_length=1000, null=True, blank=True)

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from captcha.fields import ReCaptchaField


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField(label="Your Email")
    captcha = ReCaptchaField()

home/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.core.mail import send_mail

from fixtures.models import Competition
from home.forms import ContactForm


def index(request):
    return render(request, 'home/index.html')


def rules(request):
    nehl = get_object_or_404(Competition, pk=1)
    return render(request, 'home/rules.html', {"competition": nehl})


def help(request):
    return render(request, 'home/help.html')


def contact(request):

    if request.method == 'POST':

        form = ContactForm(request.POST)

        if form.is_valid():
            subject = "NEHL WEB CONTACT - " + form.cleaned_data['subject']
            sender = "notifications@northeasthockeyleague.org"
            message = "The following message was sent from the web contact form: \r\n\r\n" + \
                      form.cleaned_data['message'] + "\r\n\r\n" + \
                      "The message was sent by " + form.cleaned_data['sender']

            nehl = get_object_or_404(Competition, pk=1)

            recipients = []
            for official in nehl.officials.all():
                if official.type == 0:
                    try:
                        if official.user is not None:
                            recipients.append(official.user.email)
                    except:
                        pass

            send_mail(subject, message, sender, recipients)

            return HttpResponseRedirect('thanks')

    else:
        form = ContactForm()
    return render(request, 'home/contact.html',  {'form': form})


def thanks(request):
    return render(request, 'home/thanks.html')

home/templates/home/contact.html
{% extends 'nehlwebsite/base.html' %}

{% load static %}
{% load crispy_forms_filters %}

{% block css %}

    <link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}">

{% endblock %}

{% block content %}

    <div class="container">
        <div class="jumbotron">
            <h1 class="display-4">Contact Us</h1>
        </div>

        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-success" value="Submit">
        </form>
    </div>

{% endblock %}

home/templates/home/help.html
{% extends 'nehlwebsite/base.html' %}

{% load static %}

{% block css %}

    <link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}">

{% endblock %}

{% block content %}

    <div class="container">
        <div class="jumbotron">
            <h2 class="display-4">Help</h2>
            <p class="lead">
                Instructions on how to use this website.
            </p>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title">Completing a match card</h3>
                        <a class="btn btn-primary" role="button" href="{% static 'help/completing_a_match_card.pdf' %}" target="_blank">View</a>
                    </div>
                </div>
            </div>
        </div>

    </div>

{% endblock %}

home/templates/home/index.html
{% extends 'nehlwebsite/base.html' %}

{% load static %}

{% block css %}

    <link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}">

{% endblock %}

{% block content %}

    <div class="container-fluid banner-container">
        <div class="row banner">
            <div class="col">
                <div class="banner-title-container">
                    <h1 class="banner-title">NORTH EAST HOCKEY LEAGUE</h1>
                    <a role="button" class="btn btn-lg btn-primary btn-block text-white mt-4"
                       href="{% url 'clubs:index' %}">Find a club</a>
                </div>

            </div>
            <div class="col">
                <div class="banner-image"></div>
            </div>
        </div>
    </div>


    <div class="container">
        <div class="content-header">
            <h2 class="display-4">About Us</h2>
            <p class="lead">
                The North East Hockey League is a (field) hockey league based in the north east of England.
            </p>
        </div>
        <div class="row">
            <div class="col">
                <p>The North East Hockey League exists to promote outdoor hockey in Durham & Northumberland. It is
                    currently divided into 4 divisions, with Division 4 acting as a more relaxed, Conference-style
                    league.</p>
                <p>In 1956, Ashmores Hockey Club (formed by employees of Davey Ashmores Ltd of Stockton) wrote to local
                    clubs asking for support for a proposed league in County Durham. At the time, all clubs were playing
                    matches as friendlies, though teams tended to play the same clubs on the same weekends year-to-year.
                    At the 1971 Durham County AGM, Sunderland, one of the stronger clubs in the area, resurrected the
                    idea, and proposed that Northumberland be included.</p>
                <p>The first season was 1972/73 and consisted of the first XIs of 18 clubs. Clubs were expected to play
                    60% of other clubs to determine league positions, with league positions based on a win precentage.
                    Sunderland was the inaugural winner with an 88% success rate, followed by Furness on 78%. The first
                    committee was chaired by Ken Burton assisted by Jim Rutherford as secretary, with Eric Ryan becoming
                    the league's first elected Secretary. </p>
                <p>From those early league matches it was obvious that impartial umpiring was badly needed. Eric Ryan
                    was instrumental in the setting up what is now the Northumberland & Durham Hockey Umpires
                    Association (NDHUA) to provide neutral umpires for league games.</p>
                <p>In 1973 the number of clubs increased to 21 a separate league for second XIs was started, also with
                    21 teams. 1975 saw the leagues split into two divisions in each league, with 12 teams in each
                    division. After the formation of the Northern Premier League the winner was promoted automatically
                    into it, which increased the interest and standard of play in the North East.</p>
                <p>In 1991 the league became an open integrated arrangement, with the first XI league becoming Divisions
                    1 and 2, and the second XI league Divisions 3 and 4, and league hockey being opened up to any club
                    side wanting to participate. 1998 saw the Conference division appear for the first time, for lower
                    sides wishing to participate within a more relaxed format. In 2007 this became the Club Development
                    League.</p>
                <p>In 2019 England Hockey reorganised the national leagues, increasing the number of teams from 40 to
                    60. The subsequent reorganization led to the NEHL Premier League (what was the first XI league, then
                    Division 1) becoming Division 3 North East of the North League.</p>
            </div>
        </div>
    </div>

{% endblock %}

home/templates/home/rules.html
{% extends 'nehlwebsite/base.html' %}

{% load static %}

{% block css %}

    <link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}">

{% endblock %}

{% block content %}

    <div class="container">
        <div class="jumbotron">
            <h2 class="display-4">Rules</h2>
            <p class="lead">
                These rules govern North East Hockey League competitions.
            </p>
        </div>

        <div class="alert alert-dark" role="alert">
            Download the full set of rules <a href="{% static 'NEHLRules.xlsx' %}" target="_blank" class="alert-link">here</a>.
        </div>

        <div class="alert alert-danger" role="alert">
            The interactive rules below are incomplete.
        </div>

        <div class="accordion" id="accordionExample">
            {% for ruleset in competition.rules.all %}
                <div class="card">
                    <div class="card-header" id="headingOne">
                        <h2 class="mb-0">
                            <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#ruleset-{{ ruleset.number }}"
                                    aria-expanded="false" aria-controls="collapseOne">
                                {{ ruleset.number }}. {{ ruleset.name }}
                            </button>
                        </h2>
                    </div>
                    <div id="ruleset-{{ ruleset.number }}" class="collapse" aria-labelledby="headingOne"
                         data-parent="#accordionExample">
                        <div class="card-body p-3 p-md-4">
                            {% for rule in ruleset.rules.all %}
                                <div class="row mb-2">
                                    <div class="p-0 col-2 col-sm-1 text-right"><p>{{ ruleset.number }}.{{ rule.number }}</p></div>
                                    <div class="col">
                                        {% for paragraph in rule.ruleparagraph_set.all %}
                                            <p class="my-0 mb-1">{{ paragraph.content }}</p>
                                        {% endfor %}
                                        {% for penalty in rule.penalty.all %}
                                            <p class="my-0 small text-danger">{{ penalty.description }}</p>
                                        {% endfor %}
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

home/templates/home/thanks.html
{% extends 'nehlwebsite/base.html' %}

{% load static %}
{% load crispy_forms_filters %}

{% block css %}

    <link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}">

{% endblock %}

{% block content %}

    <div class="container">
        <div class="jumbotron">
            <h1 class="display-4">Contact Us</h1>
        </div>

        <div class="alert alert-success" role="alert">
          Your message has been sent! Someone will be in touch.
        </div>
    </div>

{% endblock %}