clubs/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path


from . import views

app_name = 'clubs'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:club_id>/', views.detail, name='detail'),
    path('<int:club_id>/manage/', views.manage, name='manage'),
    path('<int:club_id>/manage/contacts/', views.edit_club_contacts, name='edit-contacts'),
    # path('manage/<int:club_id>/umpires/', views.edit_club_umpires, name='edit-umpires'),
    path('<int:club_id>/members/', views.MemberList.as_view(), name='members-list'),
    path('api/<int:club_id>/members/', views.ClubMemberListAPI.as_view(), name='api-members-list'),
    path('api/members/', views.MemberListAPI.as_view(), name='api-all-members-list'),
    path('<int:club_id>/members/<int:pk>/', views.MemberDetail.as_view(), name='members-detail'),
    path('<int:club_id>/members/request-transfer/', views.request_transfer, name='request-transfer'),
    path('transfer/', views.AdminMemberTransfer.as_view(), name='admin-member-transfer'),
    path('members/register/', views.AdminMemberRegister.as_view(), name='admin-member-register'),
    path('<int:club_id>/admin/set-main-contact/', views.AdminSetMainClubContact.as_view(), name='admin-set-main-contact')
]

home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('rules', views.rules, name='rules'),
    path('contact', views.contact, name='contact'),
    path('thanks', views.thanks, name='thanks'),
    path('help', views.help, name='help')
]

nehlwebsite/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

from . import settings

from nehlwebsite import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('clubs/', include('clubs.urls')),
    path('fixtures/', include('fixtures.urls.fixtures')),
    path('fixtures/cancellations/', include('fixtures.urls.cancellations')),
    path('fixtures/rearrangements/', include('fixtures.urls.rearrangements')),
    path('fixtures/competitions/', include('fixtures.urls.competitions')),
    path('teams/', include('teams.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile', views.profile, name='profile')
]

# urlpatterns += path(settings.MEDIAFILES_LOCATION, 'https://nehl-web-files.s3.eu-west-2.amazonaws.com/')

clubs/forms.py
from django import forms

from clubs.models import Club, ClubManagementPosition, Member
from fixtures.models import Umpire

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django_select2.forms import HeavySelect2Widget, ModelSelect2Widget


class TransferRequestForm(forms.Form):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    date_of_birth = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    transfer_from = forms.ModelChoiceField(queryset=Club.objects.all(), empty_label="Non-NEHL Club", required=False)
    evidence = forms.FileField(required=False)


class ClubManagementPositionWidget(forms.TextInput):
    def format_value(self, value):
        user = Member.objects.get(pk=value).user
        return user.first_name + ' ' + user.last_name


class EditClubManagementForm(forms.ModelForm):

    class Meta:
        model = ClubManagementPosition
        exclude = []
        widgets = {
            'holder': ClubManagementPositionWidget(),
            'type': forms.TextInput(),
            'club': forms.HiddenInput()
        }
        labels = {
            'type': 'Position'
        }

    def __init__(self, club, *args, **kwargs):
        super().__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            self.fields['holder'].disabled = True
        else:
            self.fields['holder'].widget = HeavySelect2Widget(
                data_url='/clubs/api/' + str(club.id) + '/members/'
            )


ClubManagementFormSet = forms.modelformset_factory(
    ClubManagementPosition,
    form=EditClubManagementForm,
    exclude=('club', ),
    can_delete=True
)


class ClubManagementFormSetHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(ClubManagementFormSetHelper, self).__init__(*args, **kwargs)
        self.template = 'bootstrap/table_inline_formset.html'
        self.add_input(Submit('submit', 'Save Changes'))


UmpireFormSet = forms.modelformset_factory(
    Umpire,
    exclude=(),
)


class UmpireFormSetHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(UmpireFormSetHelper, self).__init__(*args, **kwargs)
        self.template = 'bootstrap/table_inline_formset.html'
        self.add_input(Submit('submit', 'Save Changes'))


class MemberRegistrationForm(forms.Form):
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    date_of_birth = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))


class AdminMemberTransferForm(forms.Form):
    member = forms.ModelChoiceField(queryset=Member.objects.all(),
                                    widget=HeavySelect2Widget(data_url='/clubs/api/members/'))
    new_club = forms.ModelChoiceField(queryset=Club.objects.all())


class AdminMemberRegisterForm(forms.Form):
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    club = forms.ModelChoiceField(queryset=Club.objects.all())
    date_of_birth = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))


class AdminSetMainClubContactForm(forms.Form):
    def __init__(self, club_id, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['new_contact'] = forms.ModelChoiceField(
            queryset=Member.objects.filter(club_id=club_id)
        )
        self.fields['new_contact'].widget = HeavySelect2Widget(
            data_url='/clubs/api/' + str(club_id) + '/members/'
        )

clubs/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.postgres.search import SearchVector
from django.db.models import Value
from django.db.models.functions import Concat
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseForbidden, HttpResponseBadRequest
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, FormView
from rest_framework.generics import GenericAPIView
from rest_framework.mixins import ListModelMixin

from clubs.models import Club, Member, TransferRequest, ClubManagementPosition
from clubs.forms import TransferRequestForm, ClubManagementFormSet, \
    ClubManagementFormSetHelper, AdminMemberTransferForm, AdminMemberRegisterForm, AdminSetMainClubContactForm
from clubs.serializers import MemberSerializer, MemberPlusDOBSerializer
from clubs.utils import can_administrate_club

from nehlwebsite.utils.auth_utils import can_manage_club

import datetime


def index(request):
    clubs = Club.objects.order_by("name").all()
    return render(request, 'clubs/index.html', {'clubs': clubs})


def detail(request, club_id):
    club = get_object_or_404(Club, pk=club_id)
    can_manage = False
    user = request.user

    if user.is_authenticated:
        if can_manage_club(user.id, club_id):
            can_manage = True

    if club.secondary_colour == '#000000':
        light_or_dark = 'dark'
    else:
        light_or_dark = 'light'

    return render(request, 'clubs/detail.html',
                  {'club': club,
                   'can_manage': can_manage,
                   'light_or_dark': light_or_dark})


@login_required
def manage(request, club_id):
    club = get_object_or_404(Club, pk=club_id)
    can_manage = False
    user = request.user

    if can_manage_club(user.id, club_id):
        can_manage = True

    if not can_manage:
        return HttpResponseForbidden()

    context = {
        'club': club,
        'membership_size': club.members.count()
    }

    return render(request, 'clubs/manage.html', context)


@login_required
def request_transfer(request, club_id):
    club = get_object_or_404(Club, pk=club_id)
    can_manage = False
    user = request.user

    if can_manage_club(user.id, club_id):
        can_manage = True

    if not can_manage:
        return HttpResponseForbidden()

    if request.method == 'POST':

        form = TransferRequestForm(request.POST, request.FILES)

        if form.is_valid():

            if 'evidence' in form.files:
                evidence = form.files['evidence']
            else:
                evidence = None

            now = datetime.datetime.now()
            transfer_request = TransferRequest(
                datetime_submitted=now,
                submitter=user.member,
                first_name=form.cleaned_data['first_name'],
                last_name=form.cleaned_data['last_name'],
                date_of_birth=form.cleaned_data['date_of_birth'],
                transfer_from=form.cleaned_data['transfer_from'],
                transfer_to=club,
                evidence=evidence
            )
            transfer_request.save()

            msg_html = render_to_string('email/transfer-request-email.html',
                                        {'request': transfer_request})
            msg_plain = render_to_string('email/transfer-request-email.txt',
                                         {'request': transfer_request})

            send_mail(
                'Transfer Request',
                msg_plain,
                'notifications@northeasthockeyleague.org',
                ['danbaxter@live.co.uk', 'nehlsecretary@gmail.com', 'nehlc@live.co.uk'],
                html_message=msg_html,
            )

            return render(request, 'clubs/members/transfer-request-sent.html')

    elif request.method == 'GET':

        form = TransferRequestForm()

    else:
        return HttpResponseBadRequest()

    return render(request, 'clubs/members/transfer-request.html', {'form': form})


@login_required
def edit_club_contacts(request, club_id):
    club = get_object_or_404(Club, pk=club_id)
    user = request.user
    can_manage = False

    if can_manage_club(user.id, club_id):
        can_manage = True

    if not can_manage:
        return HttpResponseForbidden()

    if request.method == 'GET':
        formset = ClubManagementFormSet(queryset=ClubManagementPosition.objects.filter(club=club),
                                        form_kwargs={'club': club})
        for form in formset:
            form.fields['holder'].queryset = Member.objects.none()

    elif request.method == 'POST':
        formset = ClubManagementFormSet(request.POST,
                                        queryset=ClubManagementPosition.objects.filter(club=club),
                                        form_kwargs={'club': club})
        for form in formset:
            form.fields['holder'].queryset = Member.objects.filter(club=club)

        for form in formset.extra_forms:
            form.instance.club = club

        if formset.is_valid():
            formset.save()

        formset = ClubManagementFormSet(queryset=ClubManagementPosition.objects.filter(club=club),
                                        form_kwargs={'club': club})
        for form in formset:
            form.fields['holder'].queryset = Member.objects.filter(club=club)

    else:
        return HttpResponseBadRequest()

    return render(request, 'clubs/contacts/edit.html', {'formset': formset, 'helper': ClubManagementFormSetHelper()})


# @login_required
# def edit_club_umpires(request, club_id):
#     club = get_object_or_404(Club, pk=club_id)
#     user = request.user
#     can_manage = False
#
#     if can_manage_club(user.id, club_id):
#         can_manage = True
#
#     if not can_manage:
#         return HttpResponseForbidden()
#
#     # if request.method == 'GET':
#     formset = UmpireFormSet()
#
#     return render(request, 'clubs/umpires/edit.html', {'formset': formset, 'helper': UmpireFormSetHelper()})


class MemberList(LoginRequiredMixin, ListView):
    model = Member
    context_object_name = 'members'
    template_name = 'clubs/members/list.html'
    paginate_by = 10
    login_url = '/accounts/login/'

    def get_queryset(self):
        queryset = Member.objects.filter(
            club=get_object_or_404(Club, pk=self.kwargs['club_id'])
        )
        if 'search' in self.request.GET:
            if self.request.GET['search'] != '':
                search_term = self.request.GET.get('search', '')
                queryset = queryset.annotate(
                    search=Concat('user__first_name', Value(' '), 'user__last_name')
                ).filter(
                    search__icontains=search_term
                )
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(MemberList, self).get_context_data(**kwargs)
        context['search'] = self.request.GET.get('search', '')
        context['club_id'] = self.kwargs['club_id']
        return context

    def dispatch(self, request, *args, **kwargs):

        if not can_manage_club(request.user.id, self.kwargs['club_id']):
            return HttpResponseForbidden()

        return super(MemberList, self).dispatch(request, *args, **kwargs)


class ClubMemberListAPI(ListModelMixin,
                        GenericAPIView):
    model = Member
    serializer_class = MemberSerializer

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)

    def get_queryset(self):
        queryset = Member.objects.filter(
            club=get_object_or_404(Club, pk=self.kwargs['club_id'])
        )
        if 'search' in self.request.GET:
            if self.request.GET['search'] != '':
                search_term = self.request.GET.get('search', '')
                queryset = queryset.annotate(
                    search=Concat('user__first_name', Value(' '), 'user__last_name')
                ).filter(
                    search__icontains=search_term
                )
        return queryset


class MemberListAPI(ListModelMixin, GenericAPIView):
    model = Member
    serializer_class = MemberPlusDOBSerializer

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)

    def get_queryset(self):
        queryset = Member.objects.all()
        if 'search' in self.request.GET:
            if self.request.GET['search'] != '':
                search_term = self.request.GET.get('search', '')
                queryset = queryset.annotate(
                    # search=SearchVector('user__first_name', 'user__last_name'),
                    full_name=Concat('user__first_name', Value(' '), 'user__last_name'),
                ).filter(
                    full_name__icontains=search_term
                )
        return queryset


class MemberDetail(LoginRequiredMixin, DetailView):
    model = Member
    context_object_name = 'member'
    template_name = 'clubs/members/detail.html'
    login_url = '/accounts/login/'

    def dispatch(self, request, *args, **kwargs):

        if not can_manage_club(request.user.id, self.kwargs['club_id']):
            return HttpResponseForbidden()

        return super(MemberDetail, self).dispatch(request, *args, **kwargs)


class AdminMemberTransfer(LoginRequiredMixin, FormView):
    form_class = AdminMemberTransferForm
    template_name = 'clubs/members/admin-transfer.html'
    success_url = '/accounts/profile'

    def form_valid(self, form):
        member = form.cleaned_data['member']
        new_club = form.cleaned_data['new_club']
        member.club = new_club
        member.save()
        return super().form_valid(form)


class AdminMemberRegister(LoginRequiredMixin, FormView):

clubs/templates/clubs/members/admin-register.html
{% extends 'nehlwebsite/base.html' %}

{% load static %}
{% load crispy_forms_filters %}

{% block css %}

    <link rel="stylesheet" type="text/css" href="{% static 'clubs/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />

{% endblock %}

{% block content %}

    <div class="container">

        <div class="jumbotron">
              <h1 class="display-4">Admin Register Member</h1>
        </div>

        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-success" value="Submit">
        </form>

    </div>

{% endblock %}

{% block scripts %}
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    <script>
    $('.heavyselect2widget').select2({
      ajax: {
        url: '/clubs/api/members/',
        data: function (params) {
          debugger;
          var query = {
            search: params.term,
            format: 'json'
          };
          return query;
        }
      }
    });
    </script>
{% endblock %}

clubs/templates/clubs/members/admin-transfer.html
{% extends 'nehlwebsite/base.html' %}

{% load static %}
{% load crispy_forms_filters %}

{% block css %}

    <link rel="stylesheet" type="text/css" href="{% static 'clubs/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />

{% endblock %}

{% block content %}

    <div class="container">

        <div class="jumbotron">
              <h1 class="display-4">Admin Transfer Member</h1>
        </div>

        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-success" value="Submit">
        </form>

    </div>

{% endblock %}

{% block scripts %}
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    <script>
    $('.heavyselect2widget').select2({
      ajax: {
        url: '/clubs/api/members/',
        data: function (params) {
          debugger;
          var query = {
            search: params.term,
            format: 'json'
          };
          return query;
        }
      }
    });
    </script>
{% endblock %}

clubs/templates/clubs/members/detail.html
{% extends 'nehlwebsite/base.html' %}

{% load static %}

{% block title %}

    Member

{% endblock %}

{% block css %}

    <link rel="stylesheet" type="text/css" href="{% static 'clubs/style.css' %}">

{% endblock %}
{% block content %}

    <div class="container">

        <h1 class="display-4 my-3">Member</h1>

        <hr class="mb-4"/>

        <div class="row">

            <div class="col-12 col-md-3 mb-3">
                <button class="btn btn-block btn-primary dropdown-toggle" type="button"
                                        id="dropdownMenuButton"
                                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Manage
                                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

                </div>

            </div>

            <div class="col-12 col-md-9">

                <div class="card">
                    <div class="card-header">
                        Details
                    </div>
                    <div class="card-body">
                        <h6 class="mb-1">Name</h6>
                        <p class="mb-2">{{ member }}</p>
                        <h6 class="mb-1">Date of Birth</h6>
                        <p class="mb-2">{{ member.date_of_birth }}</p>
                        <h6 class="mb-1">Date of Registration</h6>
                        <p class="mb-1">{{ member.registration_date }}</p>
                    </div>
                </div>
            </div>


        </div>

    </div>

{% endblock %}

clubs/templates/clubs/members/list.html
{% extends 'nehlwebsite/base.html' %}

{% load static %}
{% load paginate %}

{% block css %}

    <link rel="stylesheet" type="text/css" href="{% static 'clubs/style.css' %}">

{% endblock %}

{% block content %}

    <div class="container">

        <h2 class="display-4 py-4">Members</h2>

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb mx-n3">
                <li class="breadcrumb-item"><a href="{% url 'clubs:manage' club_id %}">Manage</a></li>
                <li class="breadcrumb-item active" aria-current="page">Members</li>
            </ol>
        </nav>

        <div class="row mb-4">
            <div class="card">
                <div class="card-header">
                    <a  data-toggle="collapse" href="#test" role="button" aria-expanded="false" aria-controls="collapseExample">Search</a>
                </div>
                <div class="card-body collapse" id="test">
                    <form class="form-inline">
                        <div class="form-group mb-2 mr-2">
                            <label for="search" class="sr-only">Name</label>
                            <input type="text" value="{{ search }}" class="form-control" name="search" placeholder="Name"/>
                        </div>
                        <button type="submit" class="btn btn-primary mb-2">Find</button>
                    </form>
                </div>
            </div>
        </div>

        <div class="row">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Date of Birth</th>
                    <th scope="col">Date of Registration</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                {% for member in members %}
                    <tr>
                        <td>{{ member }}</td>
                        <td>{{ member.date_of_birth }}</td>
                        <td>{{ member.registration_date }}</td>
                        <td>
                            <a class="btn btn-primary btn-sm" href="{% url 'clubs:members-detail' member.club.id member.id %}" role="button">More Info</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            {% if is_paginated %}
                {% paginate page_obj %}
            {% endif %}
        </div>

    </div>

{% endblock %}

clubs/templates/clubs/members/transfer-request-sent.html
{% extends 'nehlwebsite/base.html' %}

{% load static %}
{% load crispy_forms_filters %}

{% block css %}

    <link rel="stylesheet" type="text/css" href="{% static 'clubs/style.css' %}">

{% endblock %}

{% block content %}

    <div class="container">

        <div class="jumbotron">
              <h1 class="display-4">Request Player Transfer</h1>
        </div>

        <div class="alert alert-success" role="alert">
            Your transfer request has been submitted.
        </div>

    </div>

{% endblock %}

clubs/templates/clubs/members/transfer-request.html
{% extends 'nehlwebsite/base.html' %}

{% load static %}
{% load crispy_forms_filters %}

{% block css %}

    <link rel="stylesheet" type="text/css" href="{% static 'clubs/style.css' %}">

{% endblock %}

{% block content %}

    <div class="container">

        <div class="jumbotron">
              <h1 class="display-4">Request Player Transfer</h1>
        </div>

        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-success" value="Submit">
        </form>

    </div>

{% endblock %}