clubs/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path


from . import views

app_name = 'clubs'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:club_id>/', views.detail, name='detail'),
    path('<int:club_id>/manage/', views.manage, name='manage'),
    path('<int:club_id>/manage/contacts/', views.edit_club_contacts, name='edit-contacts'),
    # path('manage/<int:club_id>/umpires/', views.edit_club_umpires, name='edit-umpires'),
    path('<int:club_id>/members/', views.MemberList.as_view(), name='members-list'),
    path('api/<int:club_id>/members/', views.ClubMemberListAPI.as_view(), name='api-members-list'),
    path('api/members/', views.MemberListAPI.as_view(), name='api-all-members-list'),
    path('<int:club_id>/members/<int:pk>/', views.MemberDetail.as_view(), name='members-detail'),
    path('<int:club_id>/members/request-transfer/', views.request_transfer, name='request-transfer'),
    path('transfer/', views.AdminMemberTransfer.as_view(), name='admin-member-transfer'),
    path('members/register/', views.AdminMemberRegister.as_view(), name='admin-member-register'),
    path('<int:club_id>/admin/set-main-contact/', views.AdminSetMainClubContact.as_view(), name='admin-set-main-contact')
]

home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('rules', views.rules, name='rules'),
    path('contact', views.contact, name='contact'),
    path('thanks', views.thanks, name='thanks'),
    path('help', views.help, name='help')
]

nehlwebsite/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

from . import settings

from nehlwebsite import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('clubs/', include('clubs.urls')),
    path('fixtures/', include('fixtures.urls.fixtures')),
    path('fixtures/cancellations/', include('fixtures.urls.cancellations')),
    path('fixtures/rearrangements/', include('fixtures.urls.rearrangements')),
    path('fixtures/competitions/', include('fixtures.urls.competitions')),
    path('teams/', include('teams.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile', views.profile, name='profile')
]

# urlpatterns += path(settings.MEDIAFILES_LOCATION, 'https://nehl-web-files.s3.eu-west-2.amazonaws.com/')

teams/urls.py
from django.urls import path

from . import views

app_name = 'teams'

urlpatterns = [
    path('<int:team_id>/', views.detail, name='detail')
]

clubs/models.py
from django.db import models
from django.conf import settings


class Club(models.Model):
    name = models.CharField(max_length=60)
    short_name = models.CharField(max_length=12, null=True)
    primary_colour = models.CharField(max_length=7)
    secondary_colour = models.CharField(max_length=7)
    venues = models.ManyToManyField('fixtures.Venue',
                                    through='fixtures.VenueUseType')
    main_venue = models.ForeignKey('fixtures.Venue',
                                   on_delete=models.SET_NULL,
                                   related_name='main_club',
                                   null=True)
    management = models.ManyToManyField('Member',
                                        related_name='management_position',
                                        through='ClubManagementPosition')
    main_contact = models.ForeignKey('Member',
                                     related_name='main_contact_for',
                                     on_delete=models.SET_NULL,
                                     null=True, blank=True)
    fixture_coordinator = models.ForeignKey('Member',
                                            related_name='fixture_coordinator_for',
                                            on_delete=models.SET_NULL,
                                            null=True, blank=True)
    dashboard_link = models.CharField(max_length=100, null=True, blank=True)
    is_test = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class ClubManagementPosition(models.Model):
    club = models.ForeignKey('Club', on_delete=models.CASCADE)
    holder = models.ForeignKey('Member', on_delete=models.CASCADE)
    type = models.CharField(max_length=30)

    def __str__(self):
        return self.holder.__str__()


class Member(models.Model):
    date_of_birth = models.DateField()
    registration_date = models.DateField()
    club = models.ForeignKey(Club, on_delete=models.SET_NULL, null=True, related_name='members')
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        if self.user:
            return self.user.first_name + " " + self.user.last_name
        else:
            return ''


class TransferRequest(models.Model):
    datetime_submitted = models.DateTimeField()
    submitter = models.ForeignKey(Member, on_delete=models.SET_NULL, null=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    date_of_birth = models.DateField()
    transfer_to = models.ForeignKey(
        Club, on_delete=models.SET_NULL, null=True, related_name='transfers_to')
    transfer_from = models.ForeignKey(
        Club, on_delete=models.SET_NULL, null=True, related_name='transfers_from')
    evidence = models.FileField(null=True)

fixtures/models.py
from django.db import models
from django.conf import settings

from fixtures.utils.general import get_file_path


class Season(models.Model):
    years = models.CharField(max_length=6)
    display_name = models.CharField(max_length=7)
    teams = models.ManyToManyField('teams.Team')
    competition = models.ForeignKey('fixtures.Competition', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.display_name + ' - ' + self.competition.__str__()


class Competition(models.Model):
    name = models.CharField(max_length=50)
    short_name = models.CharField(max_length=5)
    parent_competition = models.ForeignKey('Competition',
                                           on_delete=models.SET_NULL,
                                           null=True,
                                           related_name='child_competition',
                                           blank=True
                                           )
    officials = models.ManyToManyField('CompetitionOfficial', blank=True)
    rules = models.ManyToManyField('RuleSet', blank=True)
    config = models.ManyToManyField('CompetitionConfigItem', blank=True)
    current_season = models.OneToOneField('Season',
                                          on_delete=models.SET_NULL,
                                          related_name='competition_current',
                                          null=True, blank=True)

    def __str__(self):
        return self.name


class CompetitionConfigItem(models.Model):
    key = models.CharField(max_length=25)
    value = models.BooleanField()

    def __str__(self):
        return self.key + ': ' + self.value.__str__()


class LeagueStanding(models.Model):
    league = models.ForeignKey('Competition', on_delete=models.CASCADE)
    team = models.ForeignKey('teams.Team', on_delete=models.CASCADE)
    season = models.ForeignKey('Season', on_delete=models.CASCADE)
    num_played = models.PositiveIntegerField(default=0)
    num_won = models.PositiveIntegerField(default=0)
    num_lost = models.PositiveIntegerField(default=0)
    num_drawn = models.PositiveIntegerField(default=0)
    goal_difference = models.IntegerField(default=0)
    total_points = models.IntegerField(default=0)


class Penalty(models.Model):
    description = models.CharField(max_length=400)

    def __str__(self):
        return self.description

    class Meta:
        verbose_name_plural = 'penalties'


class Rule(models.Model):
    number = models.IntegerField()
    penalty = models.ManyToManyField('Penalty', blank=True)

    class Meta:
        ordering = ['number']

    def __str__(self):
        return self.ruleset_set.first().__str__() + " - " + self.number.__str__()


class RuleSet(models.Model):
    number = models.IntegerField()
    name = models.CharField(max_length=50)
    rules = models.ManyToManyField('Rule', blank=True)

    class Meta:
        ordering = ['number']

    def __str__(self):
        return self.name


class RuleParagraph(models.Model):
    number = models.IntegerField()
    content = models.CharField(max_length=500)
    rule = models.ForeignKey('Rule', on_delete=models.CASCADE)

    class Meta:
        ordering = ['number']

    def __str__(self):
        return self.content


class Venue(models.Model):
    name = models.CharField(max_length=50)
    street_name = models.CharField(max_length=50, default='')
    postcode = models.CharField(max_length=10)

    def __str__(self):
        return self.name


class VenueUseType(models.Model):
    user = models.ForeignKey('clubs.Club', on_delete=models.CASCADE)
    venue = models.ForeignKey(Venue, on_delete=models.CASCADE)
    use_type = models.CharField(max_length=30)


class Fixture(models.Model):
    season = models.ForeignKey(Season, on_delete=models.CASCADE)
    competition = models.ForeignKey(Competition, on_delete=models.CASCADE)
    venue = models.ForeignKey(Venue, on_delete=models.SET_NULL, null=True, blank=True)
    team_a = models.ForeignKey('teams.Team',
                               related_name='team_a_fixtures',
                               on_delete=models.CASCADE,
                               null=True
                               )
    team_b = models.ForeignKey('teams.Team',
                               related_name='team_b_fixtures',
                               on_delete=models.CASCADE,
                               null=True
                               )
    date = models.DateField()
    time = models.TimeField(null=True, blank=True)
    umpire_a = models.ForeignKey('Umpire',
                                 related_name='fixtures_as_umpire_a',
                                 on_delete=models.SET_NULL,
                                 null=True, blank=True)
    umpire_b = models.ForeignKey('Umpire',
                                 related_name='fixtures_as_umpire_b',
                                 on_delete=models.SET_NULL,
                                 null=True, blank=True)
    match_card_submission_url = models.CharField(max_length=300, null=True, blank=True)
    result = models.OneToOneField('FixtureResult', on_delete=models.CASCADE, null=True, blank=True)
    metadata = models.OneToOneField('FixtureMetadata', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.date.__str__() + ' - ' + self.team_a.__str__() + " vs " + self.team_b.__str__()


class FixtureResult(models.Model):
    team_a_score = models.PositiveSmallIntegerField(default=0)
    team_b_score = models.PositiveSmallIntegerField(default=0)
    team_a_points = models.IntegerField(default=0)
    team_b_points = models.IntegerField(default=0)
    draw = models.BooleanField(default=False)
    winner = models.ForeignKey('teams.Team', related_name='wins', on_delete=models.SET_NULL, null=True, blank=True)
    loser = models.ForeignKey('teams.Team', related_name='losses', on_delete=models.SET_NULL, null=True, blank=True)
    complete = models.BooleanField(default=False)

    def __str__(self):
        if self.draw:
            return '{team_a} - {team_b} draw'.format(team_a=self.fixture.team_a, team_b=self.fixture.team_b)
        else:
            return '{winner} beat {loser}'.format(winner=self.winner, loser=self.loser)


def get_file_path(instance, filename):
    import uuid
    import os

    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('uploads/match_cards', filename)


class FixtureMetadata(models.Model):
    match_card_image = models.ImageField(upload_to=get_file_path, null=True)
    match_card_image_submitted = models.BooleanField(default=False)
    squad_a_selected = models.BooleanField(default=False)
    squad_b_selected = models.BooleanField(default=False)
    scorers_submitted = models.BooleanField(default=False)
    personal_penalties_submitted = models.BooleanField(default=False)
    start_time_submitted = models.BooleanField(default=False)

    time_match_card_image_submitted = models.DateTimeField(null=True)
    time_squad_a_selected = models.DateTimeField(null=True)
    time_squad_b_selected = models.DateTimeField(null=True)
    time_scorers_submitted = models.DateTimeField(null=True)
    time_penalties_submitted = models.DateTimeField(null=True)
    time_match_card_complete = models.DateTimeField(null=True)
    time_start_time_submitted = models.DateTimeField(null=True)

    umpire_a_signed = models.BooleanField(null=True)
    umpire_b_signed = models.BooleanField(null=True)
    captain_a_signed = models.BooleanField(null=True)
    captain_b_signed = models.BooleanField(null=True)

    issue_detected = models.BooleanField(default=False)


class MatchEvent(models.Model):
    time_occurred = models.DurationField(null=True, blank=True)
    appearance = models.ForeignKey('Appearance', on_delete=models.SET_NULL, null=True)
    fixture = models.ForeignKey('FixtureResult', on_delete=models.CASCADE)


class Goal(MatchEvent):
    pass


class PersonalPenalty(MatchEvent):
    awarded_by = models.ForeignKey('Umpire', on_delete=models.SET_NULL, null=True)
    penalty_type = models.ForeignKey('PersonalPenaltyType', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Personal penalties'


class PersonalPenaltyType(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Player(models.Model):
    member = models.ForeignKey('clubs.Member', on_delete=models.SET_NULL, null=True, blank=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    def __str__(self):
        if self.member is None:
            return self.first_name + ' ' + self.last_name
        else:
            return self.member.__str__()


class Appearance(models.Model):
    fixture = models.ForeignKey('Fixture', on_delete=models.CASCADE)
    player = models.ForeignKey('Player', on_delete=models.CASCADE)
    team = models.ForeignKey('teams.Team', on_delete=models.CASCADE)

    def __str__(self):
        return self.team.__str__() + ': ' + self.player.__str__()


class FixtureCancellation(models.Model):
    cancellation_reporter = models.ForeignKey('clubs.Member', on_delete=models.SET_NULL, null=True)
    fixture = models.ForeignKey(Fixture, on_delete=models.CASCADE)
    datetime_cancelled = models.DateTimeField()
    cancellation_reason = models.CharField(max_length=30)
    cancelled_by_team = models.ForeignKey('teams.Team', on_delete=models.SET_NULL, null=True)
    more_info = models.CharField(max_length=150)
    response = models.ForeignKey('CancellationResponse', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.fixture.__str__()


class CancellationResponse(models.Model):
    response = models.CharField(max_length=20)
    response_by = models.ForeignKey('fixtures.CompetitionOfficial', on_delete=models.SET_NULL, null=True)
    additional_comments = models.CharField(max_length=1000, null=True, blank=True)

teams/models.py
from django.db import models


class Team(models.Model):
    name = models.CharField(max_length=30)
    short_name = models.CharField(max_length=5, null=True)
    club = models.ForeignKey('clubs.Club', on_delete=models.CASCADE)
    squad = models.ManyToManyField('clubs.Member', related_name='squads', blank=True)
    involved_in = models.ManyToManyField('fixtures.Competition', blank=True)

    def __str__(self):
        return self.club.name + " - " + self.short_name

clubs/templates/clubs/detail.html
{% extends 'nehlwebsite/base.html' %}

{% load static %}

{% block title %}
    Club: {{ club.short_name|default_if_none:club.name }}
{% endblock %}

{% block css %}

    <link rel="stylesheet" type="text/css" href="{% static 'clubs/style.css' %}">

    <style>
        .club-colour-background {
            background-color: {{ club.primary_colour }};
        }

        .club-secondary-colour-text {
            color: {{ club.secondary_colour }};
        }

</style>

{% endblock %}

{% block content %}

    <div class="container">



        <div class="card text-white py-2 pl-3 mt-3 rounded-0 border-0 club-colour-background">
            <div class="row">
                <div class="col">
                    <h2 class="card-title m-0 ml-md-2 my-3 club-secondary-colour-text">{{ club.name }}</h2>
                </div>
                {% if user.is_authenticated %}
                    {% if can_manage %}
                        <div class="col d-flex justify-content-end align-items-center">
                            <a href="{% url 'clubs:manage' club.id %}" role="button" class="btn btn-outline-{{ light_or_dark }} mr-4">Manage Club</a>
                        </div>
                    {% else %}
                        <div class="col d-flex justify-content-end align-items-center">
                            <span class="d-inline-block" tabindex="0" data-toggle="tooltip"
                                  title="You do not have permission to manage this club.">
                                <a href="#" role="button" class="btn btn-outline-{{ light_or_dark }} mr-4 disabled" disabled>Manage Club</a>
                            </span>
                        </div>
                    {% endif %}
                {% else %}
                    <div class="col d-flex justify-content-end align-items-center">
                        <span class="d-inline-block" tabindex="0" data-toggle="tooltip"
                              title="You must log in to manage your club.">
                            <a href="#" role="button" class="btn btn-outline-{{ light_or_dark }} mr-4 disabled"
                               disabled>Manage Club</a>
                        </span>
                    </div>
                {% endif %}
            </div>

        </div>

        <div class="row mt-3 d-block d-sm-none">
            <div class="col text-center">
                <a class="btn btn-outline-primary" href="#teams" role="button">Teams</a>
                {% if club.main_venue %}
                <a class="btn btn-outline-primary" href="#venue" role="button">Venue</a>
                {% endif %}
                {% if user.is_authenticated and club.management %}
                <a class="btn btn-outline-primary" href="#contacts" role="button">Contacts</a>
                {% endif %}
            </div>
        </div>

        <div class="row m-0 p-0 pt-3 justify-content-end">
            <div class="col-12 col-sm-4 m-0 p-0 h-100">
                <div class="card rounded-0 p-0 m-0 border-0 mb-3">
                    <div class="card-header border rounded-0" id="teams">
                        Teams
                    </div>
                    <div class="list-group rounded-0">
                        {% for team in club.team_set.all %}
                            {% if team.season_set.count > 0 %}
                                <a href="{% url 'teams:detail' team.id %}"
                                   class="rounded-0 list-group-item list-group-item-action">
                                    {{ team.name }}
                                </a>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>


            <div class="col-sm-8 pr-0 mx-0 pl-0 pt-0 pl-sm-3 mb-3">
                {% if club.main_venue %}
                <div class="pr-0 mx-0 pt-3 pl-0 pt-sm-0 mb-3">

                        <div class="card rounded-0 p-0 m-0 border-0">
                            <div class="card-header border rounded-0" id="venue">
                                Main Venue
                            </div>
                            <div class="card-body border border-top-0">

                                <h4>{{ club.main_venue.name }}</h4>
                                <address class="my-2">
                                    {{ club.main_venue.street_name }},
                                    {{ club.main_venue.postcode }}
                                </address>

                            </div>
                        </div>

                </div>
                {% endif %}
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link active" id="contacts-tab" data-toggle="tab" href="#contacts" role="tab" aria-controls="contacts" aria-selected="true">Contacts</a>
                        </li>
                    {% endif %}
                    {% if club.matchofficial_set.count > 0 %}
                        <li class="nav-item">
                            <a class="nav-link {% if not user.is_authenticated %}active{% endif %}" id="umpires-tab" data-toggle="tab" href="#umpires" role="tab" aria-controls="umpires" aria-selected="true">Umpires</a>
                        </li>
                    {% endif %}
                </ul>
                <div class="tab-content">
                    <div class="tab-pane show active" id="contacts" role="tabpanel">
                        {% if user.is_authenticated %}
                            {% if club.management %}
                                <div class="card rounded-0 p-0 m-0 border-0 mb-3">
                                    <div class="card-body border border-top-0 px-0 px-sm-2">
                                        <table class="table table-striped table-responsive-md">
                                            <thead>
                                            <tr>
                                                <th scope="col">Name</th>
                                                <th scope="col">Position</th>
                                                <th scope="col">Email Address</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                                {% for position in club.clubmanagementposition_set.all %}
                                                    <tr>
                                                        <td>{{ position.holder.user.first_name }} {{ position.holder.user.last_name }}</td>
                                                        <td>{{ position.type }}</td>
                                                        <td>{{ position.holder.user.email }}</td>
                                                    </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            {% endif %}
                        {% endif %}
                    </div>
                    {% if club.matchofficial_set.count > 0 %}
                        <div class="tab-pane {% if not user.is_authenticated %}show active{% endif %}" id="umpires" role="tabpanel">
                            <div class="card rounded-0 p-0 m-0 border-0 mb-3">
                                <div class="card-body border border-top-0 px-0 px-sm-2">
                                    <table class="table table-striped table-responsive-md">
                                        <thead>
                                        <tr>
                                            <th scope="col">Name</th>
                                            <th scope="col">Identification Number</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                            {% for official in club.matchofficial_set.all %}
                                                <tr>
                                                    <td>{{ official.umpire.user.first_name }} {{ official.umpire.user.last_name }}</td>
                                                    <td>{{ official.umpire.identification_number }}</td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                </div>


            </div>
        </div>


    </div>

{% endblock %}

clubs/templates/clubs/index.html
{% extends 'nehlwebsite/base.html' %}

{% load static %}

{% block css %}

    <link rel="stylesheet" type="text/css" href="{% static 'clubs/style.css' %}">

{% endblock %}

{% block content %}

    <div class="container">

{#        <div class="card search-box">#}
{#            <div class="card-body">#}
{#                <h5 class="card-title">Search Clubs</h5>#}
{#                <form class="form-inline">#}
{#                    <div class="row">#}
{#                        <label class="col-form-label mr-1 ml-3">Search by</label>#}
{#                        <div class="col">#}
{#                            <nav>#}
{#                                <div class="nav nav-pills" id="nav-tab" role="tablist">#}
{#                                    <a class="nav-item nav-link active" id="nav-profile-tab" data-toggle="tab"#}
{#                                       href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Name</a>#}
{#                                    <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab"#}
{#                                       href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false">Postcode</a>#}
{#                                </div>#}
{#                            </nav>#}
{#                        </div>#}
{#                    </div>#}
{#                    <div class="row">#}
{#                        <div class="col">#}
{#                            <div class="tab-content" id="nav-tabContent">#}
{#                                <div class="tab-pane fade show active" id="nav-profile" role="tabpanel"#}
{#                                     aria-labelledby="nav-profile-tab">#}
{#                                    <div class="form-group my-1">#}
{#                                        <input type="text" class="form-control col ml-2" id="name">#}
{#                                    </div>#}
{#                                </div>#}
{#                                <div class="tab-pane fade" id="nav-contact" role="tabpanel"#}
{#                                     aria-labelledby="nav-contact-tab">#}
{#                                    <div class="form-group my-1">#}
{#                                        <input type="text" class="form-control col ml-2" id="postcode">#}
{#                                    </div>#}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{##}
{#                </form>#}
{#            </div>#}
{#        </div>#}

        <div class="jumbotron mx-n3">
              <h1 class="display-4">Clubs</h1>
        </div>

        <div class="row">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Main Venue</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                {% for club in clubs %}
                    {% if not club.is_test %}
                        <tr>
                            <td>{{ club.name }}</td>
                            <td>{{ club.main_venue.name }}</td>
                            <td>
                                <a class="btn btn-primary btn-sm" href="{% url 'clubs:detail' club.id %}" role="button">More Info</a>
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>

    </div>

{% endblock %}

clubs/templates/clubs/manage.html
{% extends 'nehlwebsite/base.html' %}

{% load static %}

{% block title %}
    Club: {{ club.short_name|default_if_none:club.name }}
{% endblock %}

{% block css %}

    <link rel="stylesheet" type="text/css" href="{% static 'clubs/style.css' %}">

{% endblock %}

{% block content %}
    <div class="container mt-3">

        <h2 class="display-4">Manage Club</h2>
        <hr/>

        <div class="alert alert-warning" role="alert">
            This page is under development, more features will be added soon.
        </div>

        <div class="row">
            <div class="col-12 col-sm-6 mb-3">
                <div class="card">
                    <div class="card-header">Common Functions</div>
                    <div class="card-body">
                        <a class="btn btn-primary m-1" href="{% url 'clubs:request-transfer' club.id %}" role="button">Request Player Transfer</a>
                        <a class="btn btn-primary m-1" href="{% url 'clubs:edit-contacts' club.id %}" role="button">Edit Club Contacts</a>
{#                        <a class="btn btn-primary m-1" href="{% url 'clubs:edit-umpires' club.id %}" role="button">Edit Club Umpires</a>#}
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-6">
                <div class="card">
                    <div class="card-header">Club Membership</div>
                    <div class="card-body">
                        <p class="mb-2">Your club has {{ membership_size }} registered members.</p>
                        <a class="btn btn-primary mt-2" href="{% url 'clubs:members-list' club.id %}" role="button">Browse Members</a>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}