clubs/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path


from . import views

app_name = 'clubs'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:club_id>/', views.detail, name='detail'),
    path('<int:club_id>/manage/', views.manage, name='manage'),
    path('<int:club_id>/manage/contacts/', views.edit_club_contacts, name='edit-contacts'),
    # path('manage/<int:club_id>/umpires/', views.edit_club_umpires, name='edit-umpires'),
    path('<int:club_id>/members/', views.MemberList.as_view(), name='members-list'),
    path('api/<int:club_id>/members/', views.ClubMemberListAPI.as_view(), name='api-members-list'),
    path('api/members/', views.MemberListAPI.as_view(), name='api-all-members-list'),
    path('<int:club_id>/members/<int:pk>/', views.MemberDetail.as_view(), name='members-detail'),
    path('<int:club_id>/members/request-transfer/', views.request_transfer, name='request-transfer'),
    path('transfer/', views.AdminMemberTransfer.as_view(), name='admin-member-transfer'),
    path('members/register/', views.AdminMemberRegister.as_view(), name='admin-member-register'),
    path('<int:club_id>/admin/set-main-contact/', views.AdminSetMainClubContact.as_view(), name='admin-set-main-contact')
]

home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('rules', views.rules, name='rules'),
    path('contact', views.contact, name='contact'),
    path('thanks', views.thanks, name='thanks'),
    path('help', views.help, name='help')
]

nehlwebsite/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

from . import settings

from nehlwebsite import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('clubs/', include('clubs.urls')),
    path('fixtures/', include('fixtures.urls.fixtures')),
    path('fixtures/cancellations/', include('fixtures.urls.cancellations')),
    path('fixtures/rearrangements/', include('fixtures.urls.rearrangements')),
    path('fixtures/competitions/', include('fixtures.urls.competitions')),
    path('teams/', include('teams.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile', views.profile, name='profile')
]

# urlpatterns += path(settings.MEDIAFILES_LOCATION, 'https://nehl-web-files.s3.eu-west-2.amazonaws.com/')

fixtures/views.py
import datetime

from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseForbidden

from fixtures.forms import FixtureCancellationForm, MatchCardImageForm
from fixtures.models import Fixture, FixtureCancellation


def index(request):
    return HttpResponse('')


def cancel(request, fixture_id):
    fixture = get_object_or_404(Fixture, pk=fixture_id)
    can_manage_fixture = False
    user = request.user

    if user.is_authenticated:
        try:
            if user.member is not None:
                for position in user.member.management_position.all():
                    if user.member.club_id == fixture.team_a.club_id or user.member.club_id == fixture.team_b.club_id:
                        can_manage_fixture = True
        except:
            pass

    if not can_manage_fixture:
        return HttpResponseForbidden()

    if request.method == 'POST':

        form = FixtureCancellationForm(request.POST)

        if form.is_valid():
            from fixtures.utils.cancellations import send_cancellation_notifications

            now = datetime.datetime.now()
            cancellation = FixtureCancellation(
                cancellation_reporter=user.member,
                fixture=fixture,
                datetime_cancelled=now,
                cancellation_reason=form.cleaned_data['cancellation_reason'],
                more_info=form.cleaned_data['more_cancellation_info']
            )
            cancellation.save()

            send_cancellation_notifications(fixture, cancellation)

            return render(request, 'fixtures/cancellation_sent.html', {'fixture': fixture})

    elif request.method == 'GET':

        form = FixtureCancellationForm()

    else:
        return HttpResponseBadRequest()

    context = {
        'fixture': fixture,
        'form': form,
    }

    return render(request, 'fixtures/cancel.html', context)


def card_original(request):

    if request.method == 'POST':
        form = MatchCardImageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return render(request, 'fixtures/match_card_upload_success.html', {})
    else:
        form = MatchCardImageForm()
    return render(request, 'fixtures/match_card_upload.html', {
        'form': form
    })


def detail(request, fixture_id):
    fixture = get_object_or_404(Fixture, pk=fixture_id)
    can_manage_fixture = False
    user = request.user

    if user.is_authenticated:
        try:
            if user.member is not None:
                for position in user.member.management_position.all():
                    if user.member.club_id == fixture.team_a.club_id or user.member.club_id == fixture.team_b.club_id:
                        can_manage_fixture = True
        except:
            pass

    return render(request, 'fixtures/detail.html', {'fixture': fixture, 'can_manage': can_manage_fixture})

fixtures/views/cancellations.py
from django.shortcuts import render, get_object_or_404

from fixtures.models import FixtureCancellation, CancellationResponse
from fixtures.forms import CancellationResponseForm
from fixtures.utils.cancellations import can_manage_cancellation

from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.core.paginator import Paginator
from django.views.generic.edit import DeleteView


def index(request):
    cancellations = FixtureCancellation.objects.all().order_by('-fixture__date')
    user = request.user
    can_manage = False

    if user.is_authenticated:
        if can_manage_cancellation(cancellations.first(), user.id):
            can_manage = True

    if not can_manage:
        return HttpResponseForbidden()

    paginator = Paginator(cancellations, 10)

    page = request.GET.get('page')
    cancellations = paginator.get_page(page)

    return render(request, 'cancellations/index.html', {'cancellations': cancellations})


def detail(request, cancellation_id):
    cancellation = get_object_or_404(FixtureCancellation, pk=cancellation_id)
    user = request.user
    can_manage = False

    if user.is_authenticated:
        if can_manage_cancellation(cancellation, user.id):
            can_manage = True

    if not can_manage:
        return HttpResponseForbidden()

    return render(request, 'cancellations/detail.html', {'fixture': cancellation.fixture, 'cancellation': cancellation})


def respond(request, cancellation_id):
    cancellation = get_object_or_404(FixtureCancellation, pk=cancellation_id)
    user = request.user
    can_manage = False

    if user.is_authenticated:
        if can_manage_cancellation(cancellation, user.id):
            can_manage = True

    if not can_manage:
        return HttpResponseForbidden()

    if request.method == 'POST':

        form = CancellationResponseForm(request.POST)

        if form.is_valid():

            official = user.competitionofficial_set.first()

            response = CancellationResponse(
                response=form.cleaned_data['response'],
                additional_comments=form.cleaned_data['additional_comments'],
                response_by=official
            )

            response.save()

            cancellation.response = response
            cancellation.save()

            return HttpResponseRedirect('cancellations:index')

    else:
        form = CancellationResponseForm()

    return render(request, 'cancellations/respond.html', {'cancellation': cancellation, 'form': form})


class CancellationDelete(DeleteView):
    template_name = 'cancellations/confirm_delete.html'
    model = FixtureCancellation
    success_url = reverse_lazy('cancellations:index')

fixtures/views/competitions.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, ListView, FormView, TemplateView

from clubs.models import Club
from fixtures.forms import SeasonCreateForm
from fixtures.models import Competition, LeagueStanding, Season, Fixture
from nehlwebsite.utils.auth_utils import can_administrate_competition
from teams.models import Team

import pandas
from datetime import datetime


class CompetitionListView(ListView):
    model = Competition
    context_object_name = 'competitions'
    template_name = 'competitions/list.html'


class CompetitionDetailView(DetailView):
    model = Competition
    context_object_name = 'competition'
    template_name = 'competitions/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['standings'] = LeagueStanding.objects \
            .filter(league=context[self.context_object_name],
                    season=context[self.context_object_name].season_set.first()) \
            .order_by('-total_points')
        context['seasons'] = Season.objects\
            .filter(competition=context[self.context_object_name])
        return context


class CompetitionAdminView(LoginRequiredMixin, TemplateView):
    template_name = 'competitions/admin.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['competition'] = Competition.objects.get(pk=kwargs['competition'])
        return context

    def get(self, request, *args, **kwargs):
        if not can_administrate_competition(request.user.id, kwargs['competition']):
            return HttpResponseForbidden()

        return super().get(request, *args, **kwargs)


class CompetitionStandingsView(ListView):
    model = LeagueStanding
    context_object_name = 'standings'
    template_name = 'competitions/standings.html'

    def get_queryset(self):
        return LeagueStanding.objects\
            .filter(league_id=self.kwargs['competition'],
                    season_id=self.kwargs['season']) \
            .order_by('-total_points')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['competition'] = get_object_or_404(Competition,
                                                   pk=self.kwargs['competition'])
        context['season'] = get_object_or_404(Season,
                                              pk=self.kwargs['season'])
        return context


class SeasonCreateView(LoginRequiredMixin, FormView):
    form_class = SeasonCreateForm
    template_name = 'competitions/seasons/create.html'

    def post(self, request, *args, **kwargs):
        if not can_administrate_competition(request.user.id, kwargs['competition']):
            return HttpResponseForbidden()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        display_name = form.cleaned_data['display_name']
        years = form.cleaned_data['years']
        competition = Competition.objects.get(pk=self.kwargs['competition'])
        season = Season(display_name=display_name,
                        years=years,
                        competition=competition)
        season.save()
        form.files['fixtures_file'].seek(0)
        data = pandas.read_csv(form.files['fixtures_file'])
        for n, row in data.iterrows():
            date_str = row['date']
            club_a_str = row['club_a']
            team_a_str = row['team_a']
            club_b_str = row['club_b']
            team_b_str = row['team_b']

            club_a = Club.objects.get(short_name__iexact=club_a_str)
            club_b = Club.objects.get(short_name__iexact=club_b_str)

            team_a = Team.objects.get(club=club_a, short_name__iexact=team_a_str)
            team_b = Team.objects.get(club=club_b, short_name__iexact=team_b_str)

            date = datetime.strptime(date_str, '%d/%m/%Y')

            fixture = Fixture(
                team_a=team_a,
                team_b=team_b,
                date=date,
                season=season,
                competition=competition
            )

            season.teams.add(team_a, team_b)

            fixture.save()

        season.save()

        for team in season.teams.all():
            standing = LeagueStanding(
                league=competition,
                team=team,
                season=season,
                num_played=0,
                num_won=0,
                num_lost=0,
                num_drawn=0,
                goal_difference=0,
                total_points=0
            )
            standing.save()

        return super().form_valid(form)


class SeasonAdminView(LoginRequiredMixin, TemplateView):
    template_name = 'competitions/admin.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['competition'] = Competition.objects.get(pk=kwargs['competition'])
        return context

    def get(self, request, *args, **kwargs):
        if not can_administrate_competition(request.user.id, kwargs['competition']):
            return HttpResponseForbidden()
        return super().get(request, *args, **kwargs)


class SeasonIssuesView(LoginRequiredMixin, ListView):
    template_name = 'competitions/seasons/issues.html'
    context_object_name = 'fixtures'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        competition = Competition.objects.get(pk=self.kwargs['competition'])
        season = Season.objects.get(pk=self.kwargs['season'])
        context['season'] = season
        context['competition'] = competition
        return context

    def get_queryset(self):
        season = Season.objects.get(pk=self.kwargs['season'])
        fixtures = season.fixture_set.filter(metadata__issue_detected=True)
        return fixtures


    def get(self, request, *args, **kwargs):
        if not can_administrate_competition(request.user.id, kwargs['competition']):
            return HttpResponseForbidden()
        return super().get(request, *args, **kwargs)

fixtures/templates/fixtures/cancel.html
{% extends 'nehlwebsite/base.html' %}

{% load static %}
{% load crispy_forms_filters %}

{% block css %}

    <link rel="stylesheet" type="text/css" href="{% static 'fixtures/style.css' %}">

{% endblock %}

{% block content %}

    <div class="container">

        <div class="jumbotron">
            <h1 class="display-4">Cancel Fixture</h1>
        </div>

        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-success" value="Submit">
        </form>

    </div>

{% endblock %}

{% block scripts %}

    <script>
        $( function() {
            $( ".datepicker" ).datepicker();
        } );
    </script>
{% endblock %}

fixtures/templates/fixtures/cancellation_sent.html
{% extends 'nehlwebsite/base.html' %}

{% load static %}
{% load crispy_forms_filters %}

{% block css %}

    <link rel="stylesheet" type="text/css" href="{% static 'fixtures/style.css' %}">

{% endblock %}

{% block content %}

    <div class="container">

        <div class="row m-0 p-0">
            <div class="col-5 fixture-banner d-flex align-items-center justify-content-end">
                <div class="d-none d-md-block">
                    <a href="{% url 'clubs:detail' fixture.team_a.club.id %}" class="no-underline"><h2
                            class="text-right text-dark">{{ fixture.team_a.club.name }}</h2></a>
                    <h3 class="text-right">{{ fixture.team_a.name }}</h3>
                </div>
                <div class="d-block d-md-none">
                    <a href="{% url 'clubs:detail' fixture.team_a.club.id %}" class="no-underline"><h2
                            class="text-right text-dark">{{ fixture.team_a.club.short_name|default_if_none:fixture.team_a.club.name }}</h2>
                    </a>
                    <h3 class="text-right">{{ fixture.team_a.short_name }}</h3>
                </div>
            </div>
            <div class="col-2 d-flex align-items-center justify-content-center">
                <div class="d-flex versus bg-dark justify-content-center">
                    <h5 class="text-center text-white align-self-center m-0">VS</h5>
                </div>
            </div>
            <div class="col-5 d-flex align-items-center">
                <div class="d-none d-md-block">
                    <a href="{% url 'clubs:detail' fixture.team_b.club.id %}" class="no-underline"><h2
                            class="text-dark">{{ fixture.team_b.club.name }}</h2></a>
                    <h3>{{ fixture.team_b.name }}</h3>
                </div>
                <div class="d-block d-md-none">
                    <a href="{% url 'clubs:detail' fixture.team_b.club.id %}" class="no-underline"><h2
                            class="text-dark">{{ fixture.team_b.club.short_name|default_if_none:fixture.team_b.club.name }}</h2>
                    </a>
                    <h3>{{ fixture.team_b.short_name }}</h3>
                </div>
            </div>
        </div>

        <h1 class="display-4">Cancel Fixture</h1>

        <hr />


        <div class="alert alert-success" role="alert">
            Your cancellation request has been submitted.
        </div>

    </div>

{% endblock %}

{% block scripts %}

{% endblock %}

fixtures/templates/fixtures/match_card_originals.html
{% extends 'nehlwebsite/base.html' %}

{% load static %}
{% load crispy_forms_filters %}
{% load paginate %}

{% block css %}

    <link rel="stylesheet" type="text/css" href="{% static 'fixtures/style.css' %}">

{% endblock %}

{% block content %}

    <div class="container">

        <div class="jumbotron">
            <h3 class="display-4">Match Card Images</h3>
        </div>

        {% paginate match_cards %}

        <div class="list-group">
            <div class="list-group-item">
                <div class="row">
                    <p class="col">Date Uploaded</p>
                    <p class="col">Name</p>
                    <p class="col">Link</p>
                </div>
            </div>
            {% for card in match_cards %}
            <div class="list-group-item">
                <div class="row">
                    <p class="col">{{ card.uploaded_at }}</p>
                    <p class="col">{{ card.name }}</p>
                    <p class="col"><a href="{{ card.image.url }}">Link</a></p>
                </div>
            </div>

            {% endfor %}
        </div>

        <div class="mt-2">
            {% paginate match_cards %}
        </div>

    </div>


{% endblock %}

fixtures/templates/fixtures/match_card_upload.html
{% extends 'nehlwebsite/base.html' %}

{% load static %}
{% load crispy_forms_filters %}

{% block css %}

    <link rel="stylesheet" type="text/css" href="{% static 'fixtures/style.css' %}">

{% endblock %}

{% block content %}

    <div class="container">

        <div class="jumbotron">
              <h1 class="display-4">Submit Match Card Image</h1>
        </div>

        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-success" value="Submit">
        </form>

    </div>

{% endblock %}

fixtures/templates/fixtures/match_card_upload_success.html
{% extends 'nehlwebsite/base.html' %}

{% load static %}
{% load crispy_forms_filters %}

{% block css %}

    <link rel="stylesheet" type="text/css" href="{% static 'fixtures/style.css' %}">

{% endblock %}

{% block content %}

    <div class="container">

        <div class="jumbotron">
              <h1 class="display-4">Submit Match Card Image</h1>
        </div>

        <div class="alert alert-success" role="alert">
            Match card uploaded successfully.
        </div>
    </div>

{% endblock %}

fixtures/templates/fixtures/select_squad.html
{% extends 'nehlwebsite/base.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}

{% block css %}

    <link rel="stylesheet" type="text/css" href="{% static 'fixtures/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet"/>
    <style>
        .select2-selection__rendered {
            line-height: 33px !important;
        }

        .select2-container .select2-selection--single {
            height: 38px !important;
        }

        .select2-selection__arrow {
            height: 38px !important;
        }

        .add-row {
            padding-left: 18px;
        }
    </style>

{% endblock %}

{% block content %}

    <div class="container">

        <div class="jumbotron">
            <h3>Select Squad</h3>
        </div>

        <dl>
            <dt>Fixture:</dt>
            <dd>{{ fixture }}</dd>
            <dt>Team:</dt>
            <dd>{{ team }}</dd>
        </dl>

        <form method="post">

            {{ formset.management_form }}

            {% csrf_token %}

            <div id="formset">

                {% for form in formset %}

                    <div class="card my-1 member on-field-players">

                        <div class="card-body py-1">
                            {% for error in form.non_field_errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                            <div class="row align-items-center">

                                <div class="col-2 col-sm-1 px-0 pl-2 px-sm-3">
                                    {{ forloop.counter }}
                                </div>

                                <div class="col-9 col-sm-3 p-2">
                                    <div class="btn-group-toggle" data-toggle="buttons">
                                        <label onclick="toggle_registered(this)"
                                               for="{{ form.is_registered.html_name }}"
                                               id="{{ form.is_registered.id_for_label }}"
                                               class="btn btn-sm btn-secondary {% if form.is_registered.value %}active{% endif %}">
                                            <input type="checkbox" name="{{ form.is_registered.html_name }}"
                                                   checked> {{ form.is_registered.label }}
                                        </label>
                                    </div>
                                </div>

                                <div class="col-12 col-sm-8 p-2"
                                     style="{% if not form.is_registered.value %}display: none;{% endif %}">
                                    {{ form.member|as_crispy_field }}
                                </div>

                                <div class="col-12 col-sm-4 pl-2 pr-0 py-2"
                                     style="{% if form.is_registered.value %}display: none;{% endif %}">
                                    {{ form.first_name|as_crispy_field }}
                                </div>

                                <div class="col-12 col-sm-4 pl-2 pl-sm-0 pr-2 py-2"
                                     style="{% if form.is_registered.value %}display: none;{% endif %}">
                                    {{ form.last_name|as_crispy_field }}
                                </div>

                            </div>

                        </div>

                    </div>

                {% endfor %}

                {% with formset.empty_form as form %}
                    <div class="card my-1 member substitutes" id="id_empty_form" style="display:none;">

                        <div class="card-body py-1">
                            <div class="row align-items-center">

                                <div id="counter" class="col-2 col-sm-1 px-0 pl-2 pr-0">
                                    <p>Sub</p>
                                </div>

                                <div class="col-9 col-sm-3 p-2">
                                    <div class="btn-group-toggle" data-toggle="buttons">
                                        <label onclick="toggle_registered(this)"
                                               for="{{ form.is_registered.html_name }}"
                                               id="{{ form.is_registered.id_for_label }}"
                                               class="btn btn-sm btn-secondary active">
                                            <input type="checkbox" name="{{ form.is_registered.html_name }}"
                                                   checked> {{ form.is_registered.label }}
                                        </label>
                                    </div>
                                </div>

                                <div class="col-12 col-sm-8 p-2">
                                    {{ form.member|as_crispy_field }}
                                </div>

                                <div class="col-12 col-sm-4 pl-2 pr-0 py-2" style="display: none;">
                                    {{ form.first_name|as_crispy_field }}
                                </div>

                                <div class="col-12 col-sm-4 pl-2 pl-sm-0 pr-2 py-2" style="display: none;">
                                    {{ form.last_name|as_crispy_field }}
                                </div>

                                <div class="delete-row">

                                </div>

                            </div>

                        </div>


                    </div>
                {% endwith %}
            </div>

            <div class="row py-2">
                <div class="col">
                    <input type="submit" class="btn btn-primary btn-lg float-right" value="Submit"/>
                </div>
            </div>

        </form>
    </div>

{% endblock %}

{% block scripts %}
    {{ form.media.js }}
    <script type="text/javascript" src="{{ formset_js_url }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    <script id="ajax-url" type="application/json">'{% url 'clubs:api-members-list' club_id %}'</script>
    <script type="text/javascript" src="{{ page_js }}"></script>

{% endblock %}

fixtures/templates/fixtures/submit_match_card.html
{% extends 'nehlwebsite/base.html' %}

{% load static %}
{% load crispy_forms_filters %}

{% block css %}

    <link rel="stylesheet" type="text/css" href="{% static 'fixtures/style.css' %}">

{% endblock %}

{% block content %}

    <div class="container">

        <h4 class="mt-4">Complete Match Card</h4>

        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-success" value="Submit">
        </form>

    </div>

{% endblock %}

fixtures/templates/fixtures/submit_penalties.html
{% extends 'nehlwebsite/base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block css %}

    <link rel="stylesheet" type="text/css" href="{% static 'fixtures/style.css' %}">

{% endblock %}

{% block content %}

    <div class="container">

        <h4 class="mt-4">Submit Personal Penalties (Cards)</h4>

        <div class="row">
            <div class="col">
                <p>Use this form to submit the cards given out in the game, submit cards for both teams. If no cards were given just press submit without adding any.</p>
            </div>
        </div>

        <form method="post" enctype="multipart/form-data">

            {% crispy formset helper %}

            <div class="row py-2">
                <div class="col">
                    <input type="submit" class="btn btn-primary btn-lg float-left" value="Submit"/>
                </div>
            </div>

        </form>
    </div>

{% endblock %}

{% block scripts %}
    {{ form.media.js }}
    <script type="text/javascript" src="{{ formset_js_url }}"></script>
    <script type="text/javascript">
        $('.penalty-row').formset({
            addCssClass: 'btn btn-secondary btn-sm',
            deleteCssClass: 'mx-3',
            deleteText: 'Remove penalty',
            addText: 'Add a penalty',
        })
    </script>
{% endblock %}

fixtures/templates/fixtures/submit_result.html
{% extends 'nehlwebsite/base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block css %}

    <link rel="stylesheet" type="text/css" href="{% static 'fixtures/style.css' %}">

{% endblock %}

{% block content %}

    <div class="container">

        <div class="jumbotron">
            <h1 class="display-4">Submit Result</h1>
        </div>

        <div class="row m-0 p-0">
            <div class="col-5 fixture-banner d-flex align-items-center justify-content-end">
                <div class="d-none d-md-block">
                    <a href="{% url 'clubs:detail' fixture.team_a.club.id %}" class="no-underline"><h2
                            class="text-right text-dark">{{ fixture.team_a.club.name }}</h2></a>
                    <h3 class="text-right">{{ fixture.team_a.name }}</h3>
                </div>
                <div class="d-block d-md-none">
                    <a href="{% url 'clubs:detail' fixture.team_a.club.id %}" class="no-underline"><h2
                            class="text-right text-dark">{{ fixture.team_a.club.short_name|default_if_none:fixture.team_a.club.name }}</h2>
                    </a>
                    <h3 class="text-right">{{ fixture.team_a.short_name }}</h3>
                </div>
            </div>
            <div class="col-2 d-flex align-items-center justify-content-center">
                <div class="d-flex versus bg-dark justify-content-center">
                    <h5 class="text-center text-white align-self-center m-0">VS</h5>
                </div>
            </div>
            <div class="col-5 d-flex align-items-center">
                <div class="d-none d-md-block">
                    <a href="{% url 'clubs:detail' fixture.team_b.club.id %}" class="no-underline"><h2
                            class="text-dark">{{ fixture.team_b.club.name }}</h2></a>
                    <h3>{{ fixture.team_b.name }}</h3>
                </div>
                <div class="d-block d-md-none">
                    <a href="{% url 'clubs:detail' fixture.team_b.club.id %}" class="no-underline"><h2
                            class="text-dark">{{ fixture.team_b.club.short_name|default_if_none:fixture.team_b.club.name }}</h2>
                    </a>
                    <h3>{{ fixture.team_b.short_name }}</h3>
                </div>
            </div>
        </div>

        <div class="d-flex justify-content-center">
            <p class="small m-0 text-center">Venue: {{ fixture.venue.name }}</p>
        </div>
        <div class="d-flex justify-content-center">
            <p class="small m-0 text-center">
                Competition: {{ fixture.competition.parent_competition|default_if_none:"" }} {{ fixture.competition.short_name }}</p>
        </div>
        <div class="d-flex justify-content-center mb-4">
            <p class="small m-0 text-center">Date: {{ fixture.date }}</p>
        </div>

        {% crispy form %}
    </div>

{% endblock %}